export * from './SobreFinal/SobreFinalTemplate';
export * from './ComoParticipar/ComoParticiparTemplate';
export * from './Home/HomeTemplate';
export * from './Patrocinadores/PatrocinadoresTemplate';
export * from './EquipeColaboradores/EquipeColaboradoresTemplate';
export * from './AcomodacoesTurismo/AcomodacoesTurismo';
export * from './Programacao/ProgramacaoTemplate';
export * from './SobreMaratona/SobreMaratona';
export * from './CafeComLeite/CafeComLeite';
